site_name: MCW MSTP Codes
site_url: https://mcw-mstp.github.io/
repo_url: https://github.com/mcw-mstp/mcw-mstp.github.io
edit_uri: edit/main/docs

nav:
    - Home: 
        - Welcome: index.md
        - News: news.md
    - Singe Cell Seq: 
        - About: rna_seq/single_cell.md
        - Intro to scRNA seq: rna_seq/lect1/lect1.md
    - ABACUS:
        - About: abacus.md
        - Resources: abacus_resources.md
    - Resources: 
        - About: resources/resources.md
        - Pointers: resources/pointers.md
    - People: 
        - About: people/people.md
        - Individual Pages:
          - Stephen Mazurchuk: people/smazurchuk.md
    - Contributing: contributing.md
    - Intro to Python: introPython.md

theme: 
  name: material
  custom_dir: overrides
  favicon: assets/codes_favicon.svg
  logo: assets/cd.svg
  features:
    - navigation.tabs

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-4EB03M9P81
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcw-mstp
  generator: false